---
# tasks file for roles/app

    - name: Create a simple-api container
      docker_container:
        name: backend
        image: isidoreporretti/tp-devops-epf-isidore:simple-api
        networks:
          - name: "app-network"
