name: CI devops 2021 EPF
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: "master"
  pull_request:

jobs:
  build-and-test-app:
    runs-on: ubuntu-18.04

    steps:
      #checkout your GitHub code using actions/checkout@v2.3.3 and actions/setup-java@v2
       - name: Set up checkout
         uses: actions/checkout@v2.3.3

       - name: Set up JDK 11
         uses: actions/setup-java@v2

       - name: Build and test with Maven
         run:  maven package
